# Startup
exec-once=noctalia-shell

# Keyboard
xkb_layout=us,ru
xkb_variant=,
xkb_options=grp:win_space_toggle
bind=SUPER,space,switch_keyboard_layout

# Visual
gaps=2
windowrule=isfloating:1,width:70%,height:80%,appid:xdg-desktop-portal
windowrule=isfloating:1,width:70%,height:80%,appid:filepicker

# Volume and Brightness keys
bind=none,XF86AudioRaiseVolume=spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1+ -l 1.0
bind=none,XF86AudioLowerVolume=spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.1-
bind=none,XF86MonBrightnessUp=spawn,brightnessctl --class=backlight set +10%
bind=none,XF86MonBrightnessDown=spawn,brightnessctl --class=backlight set 10%-

# Mod+Return to open terminal
bind=SUPER,Return,spawn,alacritty
bind=SUPER,r,reload_config
bind=SUPER,D,spawn,noctalia-shell ipc call launcher toggle
bind=SUPER,E,spawn,nautilus
bind=SUPER,Q,killclient

# switch window status
# bind=SUPER,g,toggleglobal,
bind=SUPER,Esc,toggleoverview,0
# bind=ALT,backslash,togglefloating,
bind=SUPER,f,togglemaximizescreen,
bind=SUPER+SHIFT,f,togglefullscreen,
bind=SUPER+ALT,f,togglefakefullscreen,
# bind=SUPER,i,minimized,
# bind=SUPER,o,toggleoverlay,
# bind=SUPER+SHIFT,I,restore_minimized
bind=SUPER,z,toggle_scratchpad

# Focus window right/left
bind=SUPER,H,focusdir,left
bind=SUPER,J,focusdir,down
bind=SUPER,K,focusdir,up
bind=SUPER,L,focusdir,right

# Swap window right/left
bind=SUPER+CTRL,H,exchange_client,left
bind=SUPER+CTRL,J,exchange_client,down
bind=SUPER+CTRL,K,exchange_client,up
bind=SUPER+CTRL,L,exchange_client,right

# monitor switch
bind=SUPER,bracketleft,focusmon,left
bind=SUPER,bracketright,focusmon,right
bind=SUPER+Alt,Left,tagmon,left
bind=SUPER+Alt,Right,tagmon,right
bind=SUPER+Alt,Up,tagmon,up
bind=SUPER+Alt,Down,tagmon,down

# switch layout
bind=CTRL+SUPER,i,setlayout,tile
bind=CTRL+SUPER,l,setlayout,scroller
bind=SUPER,n,switch_layout
