# Monitors
monitorrule=name:DP-2,width:2560,height:1440,refresh:165,x:0,y:0
monitorrule=name:HDMI-A-1,width:1920,height:1080,refresh:75,x:2560,y:280

# bind=SUPER+ALT,p,toggle_monitor,HDMI-A-1
bind=SUPER+ALT,p,spawn,wlr-randr --output HDMI-A-1 --toggle

# monitor switch
bind=SUPER,bracketleft,focusmon,DP-2
bind=SUPER,bracketright,focusmon,HDMI-A-1
bind=SUPER+CTRL,bracketleft,tagmon,DP-2
bind=SUPER+CTRL,bracketright,tagmon,HDMI-A-1
