# Auto-generated by compose2nix.

{
  flakeLib,
  username,
  ...
}:
let
  version = "core11";
in
{
  imports = [
    (flakeLib.localhostReverseProxy "winapps" 8006)
  ];

  virtualisation.oci-containers.containers.winapps = {
    image = "ghcr.io/dockur/windows:5.16";
    autoStart = false;

    environment = {
      "VERSION" = "${version}";
      "USERNAME" = "bill";
      "PASSWORD" = "gates";

      "HOME" = "/home/${username}";

      "CPU_CORES" = "6";
      "DISK_SIZE" = "64G";
      "RAM_SIZE" = "4G";
    };
    volumes = [
      "/home/${username}:/shared:rw"
      "/data:/shared2:rw"
      "/data/hdd1/VMs/winapps/${version}:/storage:rw"
    ];
    ports = [
      # Map '8006' on Linux host to '8006' on Windows VM --> For VNC Web Interface @ http://127.0.0.1:8006.
      "127.0.0.1:8006:8006/tcp"

      # Map '3389' on Linux host to '3389' on Windows VM --> For Remote Desktop Protocol (RDP).
      "127.0.0.1:3389:3389/tcp"
      "127.0.0.1:3389:3389/udp"

      # Uncomment the next two lines and comment out the two above to expose RDP to the local network.
      # "3389:3389/tcp"
      # "3389:3389/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      # "--device=/dev/kvm:/dev/kvm:rwm"
      # "--device=/dev/net/tun:/dev/net/tun:rwm"
      # "--network-alias=windows"
      # "--network=winapps_default"
    ];
    devices = [
      "/dev/kvm"
      "/dev/net/tun"
    ];
  };
}
