# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.kernelParams = [
    # "zfs.zfs_arc_max=12884901888" # 12GB × (1024×1024×1024)
    "clearcpuid=514" # probable fix for errors in proton (umip: For now, expensive software emulation returns the result)
    "split_lock_detect=off" # probable fix for errors in proton(x86/split lock detection: took a split_lock trap at address)
    "usbcore.quirks=\"057e:2009:ik\""
  ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-276c86e7-7ad1-4624-ae05-37a41127565f";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-276c86e7-7ad1-4624-ae05-37a41127565f".device = "/dev/disk/by-uuid/276c86e7-7ad1-4624-ae05-37a41127565f";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-276c86e7-7ad1-4624-ae05-37a41127565f";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-276c86e7-7ad1-4624-ae05-37a41127565f";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6312-D660";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/data/ssd" = {
    device = "/dev/disk/by-uuid/bb377af3-0c22-45e1-8b0b-5a4e55a6789b";
    fsType = "ext4";
    options = [
      "rw"
      # "noatime"
    ];
  };

  fileSystems."/data/hdd1" = {
    device = "/dev/disk/by-uuid/0ea69abb-b36c-4e10-820d-597c2df3b13f";
    fsType = "ext4";
    options = [
      "rw"
      # "noatime"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
