[general]
import = ["~/.config/alacritty/themes/noctalia.toml"]

[window]
padding = { x = 10, y = 10 }
dynamic_padding = false
opacity = 0.97

[font]
size = 10.0

[env]
TERM = "xterm-256color"

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
]
